routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',['as'=>'login','uses'=>'LoginController@index']);
Route::get('logout',['as'=>'logout','uses'=>'LoginController@logout']);
Route::post('check-login',['as'=>'check.login','uses'=>'LoginController@checkLogin']);
Route::get('user-create',['as'=>'user.create','uses'=>'RegistrationController@index']);
Route::post('user-save',['as'=>'user.save','uses'=>'RegistrationController@userSave']);

Route::get('dashboard',['as'=>'dashboard','uses'=>'RegistrationController@dashboard']);

Route::get('products',['as'=>'products','uses'=>'ProductController@index']);
Route::post('product-save',['as'=>'product.save','uses'=>'ProductController@productsSave']);

Route::get('assign-product',['as'=>'assign.product','uses'=>'ProductAssignController@index']);
Route::post('assign-product-save',['as'=>'assign.product.save','uses'=>'ProductAssignController@assignProductSave']);
Route::group(['as'=>'shops.'],function(){
    Route::get('my-products',['as'=>'my.products','uses'=>'ProductController@myProducts']);
    
});
Route::group(['as'=>'user.'],function(){
    Route::get('purchase-products',['as'=>'purchase.products','uses'=>'ProductAssignController@purchaseProducts']);
    Route::post('get-shop-products',['as'=>'shops.get.products','uses'=>'ProductAssignController@getShopProducts']);
    Route::post('purchase-product-save',['as'=>'purchase.product.save','uses'=>'ProductAssignController@purchaseShopProductSave']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $primaryKey = 'product_id';
    protected $fillable = ['inventory_id','product_name','product_code','product_capacity','created_by','status'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\AssignedProduct;

class ProductController extends Controller
{
    public function index()
    {
        $products=Product::where('status',1)->where('created_by',auth()->user()->admin_id)->get();
        return view('products.index',compact('products'));
    }
    public function productsSave()
    {
        $validator = request()->validate([
            'product_name' => 'required',
            'product_code' => 'required',
            'product_capacity' => 'required'
        ]);
       $input = request()->except(['_token']);
       $input['created_by'] =  auth()->user()->admin_id;
       $input['inventory_id'] = "INT".sprintf("%04d",Product::max('product_id')+1);
       $newFridge = Product::create($input);
       return redirect()->route('products')->with('message','Product Added Successfully ');
    }
    public function myProducts()
    {
        $myProducts=AssignedProduct::where('status',1)->where('inventory_id',2)->get();
        return view('products.shopProducts',compact('myProducts'));
    }
}

resources/views/products/assignProducts.blade.php
@extends('layout.inner_layout')
@section('title','Assign')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add table Details</h3>
                        </div>
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger">
                                <ul>{{session()->get('error')}}</ul>
                            </div>
                        @endif
                         @if(session()->has('message'))
                            <div class="alert alert-success">
                                <ul>{{session()->get('message')}}</ul>
                            </div>
                        @endif
                        
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{route('assign.product.save')}}" id="staff_form" class="staff_form" method="post">
                            {!! csrf_field() !!}
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Product </label>
                                    <select class="form-control" id="product_id" name="product_id">
                                    <option value=""></option>
                                    @foreach ($products as $product)
                                        <option value="{{ $product->product_id}}">{{ $product->product_name}}</option>
                                    @endforeach
                                    </select>
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Shops</label>
                                    <select class="form-control" id="inventory_id" name="inventory_id">
                                    <option value=""></option>
                                    @foreach ($admins as $admin)
                                        <option value="{{ $admin->admin_id}}">{{ $admin->name}}</option>
                                    @endforeach
                                    </select>
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Quantity</label>
                                    <input type="text" class="form-control" name="qty" id="qty">
                                    </div>
                                </div>
                            </div>
                            
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
                    <div class="col-md-12">
                    <div class="card">
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                          <thead>
                          <tr>
                            <th>S/No</th>
                            <th>Shope</th>
                            <th>Product</th>
                            <th>Quantity</th>
                          </tr>
                          </thead>
                         <tbody>
                             @foreach($assignedProducts as $assignedProduct)
                             <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $assignedProduct->admin->name }}</td>
                                <td>{{ $assignedProduct->product->product_name }}</td>
                                <td>{{ $assignedProduct->quantity }}</td>
                              </tr>
                             @endforeach
                         </tbody>
                        </table>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@push('js')
<script src="{{ asset('public/admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
@endpush

resources/views/products/index.blade.php
@extends('layout.inner_layout')
@section('title','Task')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add table Details</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{route('product.save')}}" id="staff_form" class="staff_form" method="post">
                            {!! csrf_field() !!}
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Product Name</label>
                                    <input type="text" class="form-control" id="product_name" name="product_name"
                                        placeholder="Product Name">
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Product ID</label>
                                    <input type="text" class="form-control" id="product_code" name="product_code"
                                        placeholder="Product ID">
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Capacity of product</label>
                                    <input type="text" class="form-control" id="product_capacity" name="product_capacity"
                                        placeholder="Capacity of product">
                                    </div>
                                    
                                    
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
                    <div class="col-md-12">
                    <div class="card">
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                          <thead>
                          <tr>
                            <th>S/No</th>
                            <th>Inventory id</td>
                                <th>Product Name</td>
                                <th>Product Code</th>
                                <th>Product Capacity</th>
                          </tr>
                          </thead>
                         <tbody>
                             @foreach($products as $product)
                             <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $product->inventory_id }}</td>
                                <td>{{ $product->product_name }}</td>
                                <td>{{ $product->product_code }}</td>
                                <td>{{ $product->product_capacity }}</td>
                                
                              </tr>
                             @endforeach
                         </tbody>
                        </table>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@push('js')
<script src="{{ asset('public/admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
@endpush

resources/views/products/shopProducts.blade.php
@extends('layout.inner_layout')
@section('title','Task')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">My Product List</h3>
                        </div>
                    </div>
                </div>
                    <div class="col-md-12">
                    <div class="card">
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                          <thead>
                          <tr>
                            <th>S/No</th>
                            <th>Shope</th>
                            <th>Product</th>
                            <th>Quantity</th>
                          </tr>
                          </thead>
                         <tbody>
                             @foreach($myProducts as $assignedProduct)
                             <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $assignedProduct->admin->name }}</td>
                                <td>{{ $assignedProduct->product->product_name }}</td>
                                <td>{{ $assignedProduct->quantity }}</td>
                              </tr>
                             @endforeach
                         </tbody>
                        </table>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@push('js')
<script src="{{ asset('public/admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
@endpush

resources/views/products/userProducts.blade.php
@extends('layout.inner_layout')
@section('title','Assign')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add table Details</h3>
                        </div>
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        @if(session()->has('error'))
                            <div class="alert alert-danger">
                                <ul>{{session()->get('error')}}</ul>
                            </div>
                        @endif
                         @if(session()->has('message'))
                            <div class="alert alert-success">
                                <ul>{{session()->get('message')}}</ul>
                            </div>
                        @endif
                        
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{route('user.purchase.product.save')}}"   id="staff_form" class="staff_form" method="post">
                            {!! csrf_field() !!}
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">From Shops</label>
                                    <select class="form-control" id="from_inventory_id" name="from_inventory_id">
                                    <option value=""></option>
                                    @foreach ($admins as $admin)
                                        <option value="{{ $admin->admin_id}}">{{ $admin->name}}</option>
                                    @endforeach
                                    </select>
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Product </label>
                                    <select class="form-control" id="product_id" name="product_id">
                                    <option value=""></option>
                                    </select>
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">Quantity</label>
                                    <input type="text" class="form-control" name="qty" id="qty">
                                    </div>
                                    <div class="col-md-4">
                                    <label for="exampleInputEmail1">To Shops</label>
                                    <select class="form-control" id="to_inventory_id" name="to_inventory_id">
                                    <option value=""></option>
                                    @foreach ($admins as $admin)
                                        <option value="{{ $admin->admin_id}}">{{ $admin->name}}</option>
                                    @endforeach
                                    </select>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                </div>
                    <div class="col-md-12">
                    <div class="card">
                    <div class="card-body">
                        <table id="userProducts" class="table table-bordered table-striped" token="{{ csrf_token() }}" get-url="{{route('user.shops.get.products')}}">
                          <thead>
                          <tr>
                            <th>S/No</th>
                            <th>Shope</th>
                            <th>Product</th>
                            <th>Quantity</th>
                          </tr>
                          </thead>
                          <tbody>
                             @foreach($products as $assignedProduct)
                             <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $assignedProduct->admin->name }}</td>
                                <td>{{ $assignedProduct->product->product_name }}</td>
                                <td>{{ $assignedProduct->quantity }}</td>
                              </tr>
                             @endforeach
                         </tbody>
                        </table>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@push('js')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(document).on("change","#from_inventory_id",function() {
        var inventory_id= $(this).val();
        var dataUrl =$('#userProducts').attr('get-url');
        var token =$('#userProducts').attr('token');
        $.ajax({
              type:'POST',
              url: dataUrl,
              dataType: "json",
              data:{'_token': token,"inventory_id": inventory_id},
              success:function(response){
              var datas=response.data;
              var optn='';
                for (var i = 0; i < datas.length; i++){
                    optn +="<option value='"+datas[i].product.product_id+"' > "+datas[i].product.product_name+"</option>"
                }
                $('#product_id').html(optn);
              }
            });
    });
});
</script>
<script src="{{ asset('public/admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
@endpush